# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2021-04-27 17:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CheckUpFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_id', models.CharField(max_length=255, null=True, verbose_name='\u6587\u4ef6id')),
                ('file_name', models.CharField(max_length=255, null=True, unique=True, verbose_name='\u6587\u4ef6\u540d\u79f0')),
                ('status', models.CharField(max_length=255, null=True, verbose_name='\u72b6\u6001\uff080 \u505c\u7528\uff0c1 \u542f\u7528\uff09')),
                ('case_type', models.CharField(max_length=255, null=True, verbose_name='\u7528\u4f8b\u7c7b\u578b\uff1a1001\uff0c1002\uff0c1003')),
                ('case_type_name', models.CharField(max_length=255, null=True, verbose_name='\u7528\u4f8b\u7c7b\u578b\u540d:\u63a5\u53e3\uff0c\u6027\u80fd\uff0cUI')),
            ],
        ),
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_id', models.CharField(max_length=255, null=True, verbose_name='\u7528\u4f8b\u6587\u4ef6id')),
                ('file_name', models.CharField(max_length=255, verbose_name='\u7528\u4f8b\u6587\u4ef6\u540d\u79f0')),
                ('case_id', models.CharField(max_length=255, verbose_name='\u7528\u4f8bid')),
                ('case_name', models.TextField(null=True, verbose_name='\u7528\u4f8b\u540d\u79f0')),
                ('module', models.CharField(max_length=255, null=True, verbose_name='\u529f\u80fd\u6a21\u5757')),
                ('api_name', models.TextField(null=True, verbose_name='\u63a5\u53e3\u540d\u79f0')),
                ('case_level', models.CharField(max_length=255, null=True, verbose_name='\u7528\u4f8b\u7b49\u7ea7')),
                ('api_type', models.CharField(max_length=255, null=True, verbose_name='\u63a5\u53e3\u7c7b\u578b(post/get)')),
                ('api_url', models.CharField(max_length=255, null=True, verbose_name='\u8bf7\u6c42\u5730\u5740')),
                ('preconditions', models.CharField(max_length=255, null=True, verbose_name='\u524d\u7f6e\u6761\u4ef6')),
                ('relation', models.CharField(max_length=255, null=True, verbose_name='\u5173\u8054\u53c2\u6570')),
                ('input_params', models.CharField(max_length=255, null=True, verbose_name='\u8f93\u5165\u53c2\u6570')),
                ('expected', models.CharField(max_length=255, null=True, verbose_name='\u9884\u671f\u7ed3\u679c')),
                ('output', models.CharField(max_length=255, null=True, verbose_name='\u5b9e\u9645\u7ed3\u679c')),
                ('result', models.CharField(max_length=255, null=True, verbose_name='\u6d4b\u8bd5\u7ed3\u679c(success/fail)')),
                ('project_name', models.CharField(max_length=255, null=True, verbose_name='\u9879\u76ee\u540d\u79f0')),
                ('version', models.CharField(max_length=255, null=True, verbose_name='\u7248\u672c\u53f7')),
                ('comments', models.CharField(max_length=255, null=True, verbose_name='\u5907\u6ce8')),
                ('status', models.CharField(max_length=255, null=True, verbose_name='\u72b6\u6001\uff080\uff1a\u505c\u7528\uff0c1\uff1a\u4f7f\u7528\uff09')),
                ('insert_date', models.CharField(max_length=255, null=True, verbose_name='\u521b\u5efa\u65e5\u671f')),
                ('update_date', models.CharField(max_length=255, null=True, verbose_name='\u4fee\u6539\u65e5\u671f')),
            ],
        ),
    ]
