# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2021-04-28 11:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_id', models.CharField(max_length=255, null=True, unique=True, verbose_name='\u6d4b\u8bd5\u4efb\u52a1id')),
                ('case_name', models.CharField(max_length=255, null=True, verbose_name='\u6d4b\u8bd5\u7528\u4f8b\u540d\u79f0, list_name')),
                ('case_id', models.CharField(max_length=255, null=True, verbose_name='\u6d4b\u8bd5\u7528\u4f8bid,list_id')),
                ('next_case_id', models.CharField(max_length=255, null=True, verbose_name='\u4e0b\u4e00\u6761\u6d4b\u8bd5\u7528\u4f8bid')),
                ('now_case_id', models.CharField(max_length=255, null=True, verbose_name='\u5f53\u524d\u6d4b\u8bd5\u7528\u4f8bid')),
                ('progress', models.CharField(max_length=255, null=True, verbose_name='\u5f53\u524d\u4efb\u52a1\u8fdb\u5ea6')),
                ('status', models.CharField(max_length=255, null=True, verbose_name='\u72b6\u6001\uff080\uff1a\u8fdb\u884c\u4e2d\uff0c1\uff1a\u5b8c\u6210\uff0c2\uff1a\u7ec8\u6b62\uff09')),
                ('test_type', models.CharField(max_length=255, null=True, verbose_name='\u4efb\u52a1\u79cd\u7c7b')),
                ('api_host', models.CharField(max_length=255, null=True, verbose_name='\u6d4b\u8bd5\u5730\u5740')),
                ('start_date', models.CharField(max_length=255, null=True, verbose_name='\u5f00\u59cb\u65f6\u95f4')),
                ('end_date', models.CharField(max_length=255, null=True, verbose_name='\u7ed3\u675f\u65f6\u95f4')),
                ('name', models.CharField(max_length=255, null=True, verbose_name='\u4efb\u52a1\u540d\u79f0(\u81ea\u5b9a\u4e49\uff0c\u4f8b\u5982\u6a21\u578b\u540d\u79f0)')),
                ('tmp1', models.CharField(max_length=255, null=True, verbose_name='\u9884\u7559')),
            ],
        ),
    ]
